# Generated by Django 4.0.4 on 2022-05-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='author_user',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='assignee',
            new_name='assignee_user',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='author',
            new_name='author_user',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='author_user',
        ),
    ]
